name: mpas-jedi-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - basemap
  - bokeh
  - cartopy
  - folium
  - geopandas
  - h5netcdf
  - jupyterlab
  - jupyterlab-myst
  - matplotlib
  - mystmd
  - nbclean
  - netCDF4
  - plotly
  - s3fs
  - scipy
  - seaborn
  - uxarray
  - xarray